### PR TITLE
Add name and social media icon

### PR DESCRIPTION
**Pull request by nikkuAg**
Added a new branch named divyansh-IITian20 having the submission for the assingment of Git and Github lecture

There is a github icon and handle name of my github account and hyperlink is attached to both to the GitHub account.

### CODE REVIEW

**Comment by SuyashSalampuria** [comment]
@IITian20 Squash the commits to one commit by using interactive git rebase

Also, try to avoid using an external image file for GitHub icon. You may use [this](https://image.flaticon.com/icons/png/128/2111/2111425.png) for the image of github logo.Just add this link to the src instead of that image.  Although, this method is also correct

**Comment by nikkuAg** [comment]
When ever i am trying to use interactive rebase and squash all the commits to one and then trying to push them back to origin it showing error:

 ! [rejected]        divyansh-IITian20 -> divyansh-IITian20 (non-fast-forward)
error: failed to push some refs to 'https://github.com/IITian20/git-assignment-2021.git'

I have first pull it to local and then using git rebase -i and after chosing the option its show to conflict the issue in the assingment.md file, even after adding it back after the changes it shows this error while pushing it back

Please help to resolve

**Comment by SuyashSalampuria** [comment]
> ! [rejected] divyansh-IITian20 -> divyansh-IITian20 (non-fast-forward)
error: failed to push some refs to '
https://github.com/IITian20/git-assignment-2021.git

You may need to use force push (add a flag -f) , although it should be used very carefully. 
Also, make sure you have rebased with ```main``` branch.

**Comment by nikkuAg** [comment]
When i was resolving the conflicts the changes you made to the assignment.md file got deleted by me

**Comment by SuyashSalampuria** [comment]
@IITian20  Use better commit messages in the present tense and also use meaningful Heading for pull request

**Pull request merged**
